"""
Local-only admin tool for dudus-app (issue #31, scoped in #15).

Adds a new card to src/data/card_index.json (with an optional photo) and lets an existing
card's photo be added, replaced, or removed. Never deployed — lives outside the Next.js build
(nothing under tools/ is imported by the app or referenced by next.config.ts), reachable only by
running it locally. It edits the working tree directly; committing/PR'ing the result goes
through the normal repo workflow (ONBOARDING.md), same as any other change.

Run from the repo root:
    conda run -n ds streamlit run tools/dudu-intake/app.py
"""

import json
import re
from pathlib import Path

import fitz
import streamlit as st
from PIL import Image, ImageOps

REPO_ROOT = Path(__file__).resolve().parents[2]
CARD_INDEX_PATH = REPO_ROOT / "src" / "data" / "card_index.json"
PHOTOS_DIR = REPO_ROOT / "public" / "photos"
DUDUS_ROOT = REPO_ROOT.parent / "Dudus"

CARD_KEY_ORDER = [
    "id",
    "common_name",
    "scientific_name",
    "family",
    "order",
    "taxon_rank",
    "sourcing",
    "sections",
    "source_report_ref",
    "photo_ref",
    "reviewed_by",
    "reviewed_at",
]

# These three have no edit UI yet (only photos do) — left as clearly-a-placeholder values for a
# human to fill in by hand later, not guessed at.
DEFAULT_TAXON_RANK = "species"
DEFAULT_SOURCING = ""

ORDER_UNKNOWN_LABEL = "Unknown (fix later)"

TARGET_RATIO = 3 / 2
RATIO_TOLERANCE = 0.02

# Font sizes below come from md_to_pdf_rl.py's H1/H2 ParagraphStyles (20pt / 15pt, both bold) —
# the same converter that produced every existing lay report. A generous floor (18/12) tolerates
# minor font-substitution drift without needing exact pt matches.
TITLE_MIN_SIZE = 18
HEADING_MIN_SIZE = 12


def load_cards():
    with open(CARD_INDEX_PATH) as f:
        return json.load(f)


def save_cards(cards):
    with open(CARD_INDEX_PATH, "w") as f:
        f.write(json.dumps(cards, indent=2, ensure_ascii=False) + "\n")


def slugify(text):
    slug = re.sub(r"[^a-z0-9]+", "-", text.strip().lower())
    return slug.strip("-")


def parse_lay_report(pdf_bytes):
    """
    Extract (title, sections, error) from a lay-report PDF generated by md_to_pdf_rl.py. The
    title is the report's own H1 (the common name, as authored); every subsequent bold heading
    starts a new section, with regular-weight text collected as that section's body until the
    next heading. Returns error=None on success, or a human-readable reason parsing failed.
    """
    doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    lines = []
    for page in doc:
        for block in page.get_text("dict")["blocks"]:
            for line in block.get("lines", []):
                spans = line["spans"]
                text = "".join(s["text"] for s in spans).strip()
                if not text:
                    continue
                size = max(s["size"] for s in spans)
                bold = any("Bold" in s["font"] for s in spans)
                lines.append((text, size, bold))

    title = None
    sections = []
    current = None
    for text, size, bold in lines:
        if title is None and bold and size >= TITLE_MIN_SIZE:
            title = text
            continue
        if bold and size >= HEADING_MIN_SIZE:
            current = {"heading": text, "body": []}
            sections.append(current)
            continue
        if current is not None:
            current["body"].append(text)

    if title is None:
        return None, [], "Couldn't find a title (no large bold heading) — is this the right PDF?"
    if not sections:
        return title, [], "Found a title but no section headings — is this the lay report, not the technical one?"

    # Some reports phrase the title as a sentence ("The White-Ringed Atlas Moth") rather than a
    # bare name — no existing common_name in card_index.json starts with an article, so this is
    # always noise to drop, never a legitimate part of the name.
    title = re.sub(r"^(the|an?)\s+", "", title, flags=re.IGNORECASE)

    return title, [{"heading": s["heading"], "body": " ".join(s["body"])} for s in sections], None


def find_technical_ref(common_name, lay_filename):
    """Look for the sibling technical PDF (same name minus "-la") in Dudus/<common_name>/, per
    the naming convention every existing report follows. Empty string (not None — the schema
    doesn't allow null here) if this machine has no Dudus/ checkout or no match is found."""
    technical_filename = lay_filename.replace("-la.pdf", ".pdf")
    if technical_filename == lay_filename:
        return ""
    candidate = DUDUS_ROOT / common_name / technical_filename
    return f"{common_name}/{technical_filename}" if candidate.exists() else ""


def order_card(card):
    return {k: card.get(k) for k in CARD_KEY_ORDER}


def process_photo(uploaded_file):
    """
    Strip EXIF/GPS metadata and bake in orientation, mirroring stripPhotoMetadata.ts (#10) so
    admin-uploaded photos get the same treatment as in-app captures. Then apply the pad-to-3:2
    convention from SKILL.md: only pads (never crops) since "crop tight to the dudu" is a manual
    judgment call the tool can't make. Returns (image, warning | None).
    """
    img = Image.open(uploaded_file)
    img = ImageOps.exif_transpose(img)
    img = img.convert("RGB")

    w, h = img.size
    ratio = w / h
    warning = None

    if ratio < TARGET_RATIO - RATIO_TOLERANCE:
        target_w = round(h * TARGET_RATIO)
        padded = Image.new("RGB", (target_w, h), "white")
        padded.paste(img, ((target_w - w) // 2, 0))
        img = padded
    elif ratio > TARGET_RATIO + RATIO_TOLERANCE:
        warning = (
            f"This photo is wider than 3:2 ({w}x{h}). The tool only pads narrow photos — "
            "it won't crop into the subject automatically. Crop it tighter yourself first "
            "(see SKILL.md's photo convention), or upload as-is and expect some edge crop "
            "on the site's 3:2/4:3 views."
        )

    return img, warning


def save_photo(img, card_id, ext):
    PHOTOS_DIR.mkdir(parents=True, exist_ok=True)
    filename = f"{card_id}.{ext}"
    fmt = "PNG" if ext == "png" else "JPEG"
    img.save(PHOTOS_DIR / filename, fmt)
    return f"/photos/{filename}"


def delete_photo(photo_ref):
    if not photo_ref:
        return
    path = REPO_ROOT / "public" / photo_ref.lstrip("/")
    if path.exists():
        path.unlink()


st.set_page_config(page_title="dudus-app intake", layout="wide")
st.title("dudus-app admin intake")
st.caption(
    "Local-only authoring tool — for entering already-researched content (via /dudus or "
    "/dudusonline), not for researching a species itself."
)

tab_new, tab_existing = st.tabs(["Add new card", "Existing cards"])

with tab_new:
    if "new_card_message" in st.session_state:
        st.success(st.session_state.pop("new_card_message"))

    st.session_state.setdefault("photo_uploader_version", 0)
    st.session_state.setdefault("lay_report_uploader_version", 0)

    existing_cards = load_cards()
    known_orders = sorted({c["order"] for c in existing_cards if c["order"]})

    st.subheader("Lay report")
    lay_report = st.file_uploader(
        "Upload the lay-audience PDF (from /dudus or /dudusonline)",
        type=["pdf"],
        key=f"new_lay_report_{st.session_state.lay_report_uploader_version}",
    )
    parsed_title, parsed_sections, parse_error = None, [], None
    if lay_report is not None:
        parsed_title, parsed_sections, parse_error = parse_lay_report(lay_report.getvalue())
        if parse_error:
            st.error(parse_error)
        else:
            st.success(f"Parsed '{parsed_title}' — {len(parsed_sections)} section(s).")
            with st.expander("Preview parsed sections"):
                for s in parsed_sections:
                    st.markdown(f"**{s['heading']}**")
                    st.write(s["body"])

    st.subheader("Photo")
    uploaded_photo = st.file_uploader(
        "Upload a pre-cropped photo (optional)",
        type=["jpg", "jpeg", "png"],
        key=f"new_photo_{st.session_state.photo_uploader_version}",
    )
    preview_img, photo_warning = (None, None)
    if uploaded_photo is not None:
        preview_img, photo_warning = process_photo(uploaded_photo)
        st.image(preview_img, caption="After metadata strip + 3:2 pad", width=400)
        if photo_warning:
            st.warning(photo_warning)

    st.subheader("Order")
    order_choice = st.selectbox(
        "Order", known_orders + [ORDER_UNKNOWN_LABEL], index=len(known_orders), key="new_order"
    )

    st.caption(
        "Everything else (scientific name, family, taxon rank, sourcing) has no edit UI yet — "
        "left as placeholder values for now, to fill in by hand until that exists."
    )

    st.divider()
    if st.button("Create card", type="primary"):
        errors = []
        if lay_report is None:
            errors.append("A lay report PDF is required.")
        elif parse_error:
            errors.append(parse_error)

        card_id = None
        if parsed_title:
            card_id = slugify(parsed_title)
            if not card_id:
                errors.append(f"Couldn't derive a usable id from title '{parsed_title}'.")
            elif any(c["id"] == card_id for c in existing_cards):
                errors.append(f"A card with id '{card_id}' already exists (from title '{parsed_title}').")

        if errors:
            for e in errors:
                st.error(e)
        else:
            photo_ref = None
            if uploaded_photo is not None:
                ext = "png" if uploaded_photo.type == "image/png" else "jpg"
                photo_ref = save_photo(preview_img, card_id, ext)

            new_card = order_card(
                {
                    "id": card_id,
                    "common_name": parsed_title,
                    "scientific_name": None,
                    "family": None,
                    "order": None if order_choice == ORDER_UNKNOWN_LABEL else order_choice,
                    "taxon_rank": DEFAULT_TAXON_RANK,
                    "sourcing": DEFAULT_SOURCING,
                    "sections": parsed_sections,
                    "source_report_ref": {
                        "technical": find_technical_ref(parsed_title, lay_report.name),
                        "lay": f"{parsed_title}/{lay_report.name}",
                    },
                    "photo_ref": photo_ref,
                    "reviewed_by": None,
                    "reviewed_at": None,
                }
            )
            existing_cards.append(new_card)
            save_cards(existing_cards)
            st.session_state.photo_uploader_version += 1
            st.session_state.lay_report_uploader_version += 1
            # st.rerun() below aborts this script run immediately, so a message shown here would
            # never actually reach the browser — stash it and show it after the rerun instead.
            st.session_state.new_card_message = f"Added '{parsed_title}' ({card_id}) to card_index.json."
            st.rerun()

with tab_existing:
    if "existing_card_message" in st.session_state:
        st.success(st.session_state.pop("existing_card_message"))

    cards = load_cards()
    if not cards:
        st.info("No cards yet.")
    for card in cards:
        with st.expander(f"{card['common_name']} ({card['id']})"):
            left, right = st.columns([1, 2])
            with left:
                if card["photo_ref"]:
                    photo_path = REPO_ROOT / "public" / card["photo_ref"].lstrip("/")
                    if photo_path.exists():
                        st.image(str(photo_path), width=250)
                    else:
                        st.warning(f"photo_ref set but file missing: {card['photo_ref']}")
                else:
                    st.write("No photo yet.")

            with right:
                replacement = st.file_uploader(
                    "Add / replace photo",
                    type=["jpg", "jpeg", "png"],
                    key=f"upload_{card['id']}",
                )
                if replacement is not None:
                    new_img, warn = process_photo(replacement)
                    st.image(new_img, caption="After metadata strip + 3:2 pad", width=300)
                    if warn:
                        st.warning(warn)
                    if st.button("Save photo", key=f"save_{card['id']}"):
                        delete_photo(card["photo_ref"])
                        ext = "png" if replacement.type == "image/png" else "jpg"
                        card["photo_ref"] = save_photo(new_img, card["id"], ext)
                        save_cards(cards)
                        st.session_state.existing_card_message = f"Photo saved for {card['common_name']}."
                        st.rerun()

                if card["photo_ref"]:
                    confirm = st.checkbox("Confirm removal", key=f"confirm_{card['id']}")
                    if st.button(
                        "Remove photo", key=f"remove_{card['id']}", disabled=not confirm
                    ):
                        delete_photo(card["photo_ref"])
                        card["photo_ref"] = None
                        save_cards(cards)
                        st.session_state.existing_card_message = f"Photo removed for {card['common_name']}."
                        st.rerun()

            st.divider()
            confirm_delete = st.checkbox(
                "Confirm deletion — removes this card and its photo file",
                key=f"confirm_delete_{card['id']}",
            )
            if st.button(
                "Delete card permanently",
                key=f"delete_{card['id']}",
                disabled=not confirm_delete,
            ):
                delete_photo(card["photo_ref"])
                remaining = [c for c in cards if c["id"] != card["id"]]
                save_cards(remaining)
                st.session_state.existing_card_message = (
                    f"Deleted '{card['common_name']}' ({card['id']})."
                )
                st.rerun()
