"""
Local-only admin tool for dudus-app (issue #31, scoped in #15).

Adds a new card to src/data/card_index.json (with an optional photo) and lets an existing
card's photo be added, replaced, or removed. Never deployed — lives outside the Next.js build
(nothing under tools/ is imported by the app or referenced by next.config.ts), reachable only by
running it locally. Each action publishes itself to the live site automatically (issue #34): a
throwaway git worktree (never the live working directory a running instance of this tool might
be serving out of) carries the change through a real branch -> PR -> e2e -> squash-merge cycle,
skipping the VERSION/CHANGELOG/tag ceremony and per-change issue that a code change would need,
since this is content, not a release — see ONBOARDING.md's "Automated content publishing" note.

Run from the repo root:
    conda run -n ds streamlit run tools/dudu-intake/app.py
"""

import json
import re
import shutil
import subprocess
import tempfile
import time
import uuid
from collections import Counter
from pathlib import Path

import fitz
import streamlit as st
from PIL import Image, ImageOps

REPO_ROOT = Path(__file__).resolve().parents[2]
CARD_INDEX_PATH = REPO_ROOT / "src" / "data" / "card_index.json"
PHOTOS_DIR = REPO_ROOT / "public" / "photos"
DUDUS_ROOT = REPO_ROOT.parent / "Dudus"

GITHUB_REPO = "ericgitonga/dudus-app"
CI_POLL_INTERVAL_SECONDS = 8
CI_POLL_TIMEOUT_SECONDS = 600

CARD_KEY_ORDER = [
    "id",
    "common_name",
    "scientific_name",
    "family",
    "order",
    "taxon_rank",
    "sourcing",
    "sections",
    "source_report_ref",
    "photo_ref",
    "reviewed_by",
    "reviewed_at",
]

# These three have no edit UI yet (only photos do) — left as clearly-a-placeholder values for a
# human to fill in by hand later, not guessed at.
DEFAULT_TAXON_RANK = "species"
DEFAULT_SOURCING = ""

ORDER_UNKNOWN_LABEL = "Unknown (fix later)"
ORDER_OTHER_LABEL = "Other (type manually)"

TARGET_RATIO = 3 / 2
RATIO_TOLERANCE = 0.02

# Font sizes below come from md_to_pdf_rl.py's H1/H2 ParagraphStyles (20pt / 15pt, both bold) —
# the same converter that produced every existing lay report. A generous floor (18/12) tolerates
# minor font-substitution drift without needing exact pt matches.
TITLE_MIN_SIZE = 18
HEADING_MIN_SIZE = 12


def load_cards():
    with open(CARD_INDEX_PATH) as f:
        return json.load(f)


def serialize_cards(cards):
    return (json.dumps(cards, indent=2, ensure_ascii=False) + "\n").encode()


def save_cards(cards):
    with open(CARD_INDEX_PATH, "wb") as f:
        f.write(serialize_cards(cards))


def slugify(text):
    slug = re.sub(r"[^a-z0-9]+", "-", text.strip().lower())
    return slug.strip("-")


def parse_lay_report(pdf_bytes):
    """
    Extract (title, sections, error) from a lay-report PDF generated by md_to_pdf_rl.py. The
    title is the report's own H1 (the common name, as authored); every subsequent bold heading
    starts a new section, with regular-weight text collected as that section's body until the
    next heading. Returns error=None on success, or a human-readable reason parsing failed.
    """
    doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    lines = []
    for page in doc:
        for block in page.get_text("dict")["blocks"]:
            for line in block.get("lines", []):
                spans = line["spans"]
                text = "".join(s["text"] for s in spans).strip()
                if not text:
                    continue
                size = max(s["size"] for s in spans)
                bold = any("Bold" in s["font"] for s in spans)
                lines.append((text, size, bold))

    title = None
    sections = []
    current = None
    for text, size, bold in lines:
        if title is None and bold and size >= TITLE_MIN_SIZE:
            title = text
            continue
        if bold and size >= HEADING_MIN_SIZE:
            current = {"heading": text, "body": []}
            sections.append(current)
            continue
        if current is not None:
            current["body"].append(text)

    if title is None:
        return None, [], "Couldn't find a title (no large bold heading) — is this the right PDF?"
    if not sections:
        return title, [], "Found a title but no section headings — is this the lay report, not the technical one?"

    # Some reports phrase the title as a sentence ("The White-Ringed Atlas Moth") rather than a
    # bare name — no existing common_name in card_index.json starts with an article, so this is
    # always noise to drop, never a legitimate part of the name.
    title = re.sub(r"^(the|an?)\s+", "", title, flags=re.IGNORECASE)

    return title, [{"heading": s["heading"], "body": " ".join(s["body"])} for s in sections], None


def find_technical_pdf_path(common_name, lay_filename):
    """Look for the sibling technical PDF (same name minus "-la") in Dudus/<common_name>/, per
    the naming convention every existing report follows. None if this machine has no Dudus/
    checkout or no match is found."""
    technical_filename = lay_filename.replace("-la.pdf", ".pdf")
    if technical_filename == lay_filename:
        return None
    candidate = DUDUS_ROOT / common_name / technical_filename
    return candidate if candidate.exists() else None


def find_technical_ref(common_name, lay_filename):
    """String form of find_technical_pdf_path for source_report_ref — empty string (not None,
    the schema doesn't allow null here) if there's no match."""
    path = find_technical_pdf_path(common_name, lay_filename)
    return f"{common_name}/{path.name}" if path else ""


def guess_order_from_technical(technical_path):
    """
    Every technical report states the taxonomic order in prose during its "Taxonomy and
    Classification" section (e.g. "Order Hemiptera", "belong to Order Araneae") — consistent
    enough across the corpus to regex for, though it's a heuristic over free text, not a
    structured field. Returns the most common match, or None if the file is missing or the
    pattern isn't found (caller falls back to manual entry either way).
    """
    if not technical_path:
        return None
    doc = fitz.open(str(technical_path))
    text = "\n".join(page.get_text() for page in doc)
    matches = re.findall(r"\bOrder\s+([A-Z][a-zA-Z]+)\b", text)
    if not matches:
        return None
    return Counter(matches).most_common(1)[0][0]


def order_card(card):
    return {k: card.get(k) for k in CARD_KEY_ORDER}


def process_photo(uploaded_file):
    """
    Strip EXIF/GPS metadata and bake in orientation, mirroring stripPhotoMetadata.ts (#10) so
    admin-uploaded photos get the same treatment as in-app captures. Then apply the pad-to-3:2
    convention from SKILL.md: only pads (never crops) since "crop tight to the dudu" is a manual
    judgment call the tool can't make. Returns (image, warning | None).
    """
    img = Image.open(uploaded_file)
    img = ImageOps.exif_transpose(img)
    img = img.convert("RGB")

    w, h = img.size
    ratio = w / h
    warning = None

    if ratio < TARGET_RATIO - RATIO_TOLERANCE:
        target_w = round(h * TARGET_RATIO)
        padded = Image.new("RGB", (target_w, h), "white")
        padded.paste(img, ((target_w - w) // 2, 0))
        img = padded
    elif ratio > TARGET_RATIO + RATIO_TOLERANCE:
        warning = (
            f"This photo is wider than 3:2 ({w}x{h}). The tool only pads narrow photos — "
            "it won't crop into the subject automatically. Crop it tighter yourself first "
            "(see SKILL.md's photo convention), or upload as-is and expect some edge crop "
            "on the site's 3:2/4:3 views."
        )

    return img, warning


def save_photo(img, card_id, ext):
    PHOTOS_DIR.mkdir(parents=True, exist_ok=True)
    filename = f"{card_id}.{ext}"
    fmt = "PNG" if ext == "png" else "JPEG"
    img.save(PHOTOS_DIR / filename, fmt)
    return f"/photos/{filename}"


def delete_photo(photo_ref):
    if not photo_ref:
        return
    path = REPO_ROOT / "public" / photo_ref.lstrip("/")
    if path.exists():
        path.unlink()


def run_cmd(args, cwd, check=True):
    result = subprocess.run(args, cwd=str(cwd), capture_output=True, text=True)
    if check and result.returncode != 0:
        raise RuntimeError(
            f"`{' '.join(args)}` failed (exit {result.returncode}):\n{result.stdout}\n{result.stderr}"
        )
    return result.stdout.strip()


def publish_content_change(files, commit_message, pr_title, pr_body, log):
    """
    Drive the existing branch -> PR -> e2e -> squash-merge pipeline for a content-only change,
    so using this tool actually publishes to the live site (#34) without VERSION/CHANGELOG/tag
    ceremony or a per-change issue — same reasoning as career-transition's per-client CV/plan
    exemption from issue-first (this is content, not a codebase change).

    `files` maps repo-relative paths to new bytes, or None to delete that path. Runs entirely in
    a throwaway git worktree on its own branch — never checks out anything in REPO_ROOT itself,
    so a concurrently-running instance of this same tool (or an admin's own unrelated local
    edits) in the live working directory is never disturbed.

    Returns (published: bool, pr_url: str | None, detail: str).
    """
    branch = f"intake/{uuid.uuid4().hex[:10]}"
    worktree_dir = Path(tempfile.mkdtemp(prefix="dudu-intake-publish-"))
    pr_url = None
    try:
        log("Fetching latest `main`…")
        run_cmd(["git", "fetch", "origin", "main"], REPO_ROOT)

        log(f"Preparing an isolated worktree on `{branch}`…")
        run_cmd(["git", "worktree", "add", "-b", branch, str(worktree_dir), "origin/main"], REPO_ROOT)

        for rel_path, content in files.items():
            dest = worktree_dir / rel_path
            if content is None:
                if dest.exists():
                    dest.unlink()
            else:
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_bytes(content)
            run_cmd(["git", "add", "--", rel_path], worktree_dir)

        run_cmd(["git", "commit", "-m", commit_message], worktree_dir)

        log("Pushing…")
        run_cmd(["git", "push", "-u", "origin", branch], worktree_dir)

        log("Opening PR…")
        pr_url = run_cmd(
            [
                "gh", "pr", "create", "--repo", GITHUB_REPO,
                "--title", pr_title, "--body", pr_body, "--head", branch,
            ],
            worktree_dir,
        )
        pr_number = pr_url.rstrip("/").split("/")[-1]

        log(f"PR {pr_url} opened — waiting for checks…")
        deadline = time.time() + CI_POLL_TIMEOUT_SECONDS
        checks = []
        while time.time() < deadline:
            checks_raw = run_cmd(
                ["gh", "pr", "checks", pr_number, "--repo", GITHUB_REPO, "--json", "name,bucket"],
                worktree_dir,
                check=False,
            )
            checks = json.loads(checks_raw) if checks_raw else []
            if checks and all(c["bucket"] != "pending" for c in checks):
                break
            time.sleep(CI_POLL_INTERVAL_SECONDS)
        else:
            return False, pr_url, "Timed out waiting for checks — PR left open for manual review."

        failed = [c["name"] for c in checks if c["bucket"] not in ("pass", "skipping")]
        if failed:
            return False, pr_url, f"Checks failed ({', '.join(failed)}) — PR left open, not merged."

        log("Checks green — merging…")
        run_cmd(
            ["gh", "pr", "merge", pr_number, "--repo", GITHUB_REPO, "--squash", "--delete-branch"],
            worktree_dir,
        )
        return True, pr_url, "Published to the live site."
    finally:
        log("Cleaning up the temporary worktree…")
        run_cmd(["git", "worktree", "remove", "--force", str(worktree_dir)], REPO_ROOT, check=False)
        shutil.rmtree(worktree_dir, ignore_errors=True)
        # Best-effort: if this succeeded, the live working directory's own copy of these files
        # already matches what was just merged (we published its exact current bytes), so this
        # is just bookkeeping to mark it clean — never something to block or error the UI on. Only
        # when REPO_ROOT is actually on `main` — if it's sitting on some other branch (e.g. a dev
        # session working on the tool itself), silently pulling there would be exactly the kind
        # of surprise branch-state change this worktree approach exists to avoid.
        current_branch = run_cmd(["git", "branch", "--show-current"], REPO_ROOT, check=False)
        if current_branch == "main":
            run_cmd(["git", "pull", "--ff-only"], REPO_ROOT, check=False)


def revert_local_files(paths):
    """
    Best-effort: put each path back to its last-committed (HEAD) state — restores a
    deleted/modified tracked file, removes an untracked new one. Used whenever a publish fails,
    so the local working tree never drifts ahead of `main` with content nothing else knows
    about — the next action (single or batch) always starts from a clean, HEAD-matching base.
    """
    for rel_path in paths:
        full = REPO_ROOT / rel_path
        tracked = subprocess.run(
            ["git", "ls-files", "--error-unmatch", rel_path],
            cwd=REPO_ROOT, capture_output=True, text=True,
        ).returncode == 0
        if tracked:
            run_cmd(["git", "checkout", "HEAD", "--", rel_path], REPO_ROOT, check=False)
        elif full.exists():
            full.unlink()


def do_publish(files, commit_message, pr_title, pr_body):
    with st.status("Publishing to the live site…", expanded=True) as status:
        try:
            published, pr_url, detail = publish_content_change(
                files, commit_message, pr_title, pr_body, status.write
            )
        except Exception as e:
            status.update(label="Publish failed", state="error")
            st.error(f"Publish failed: {e}")
            revert_local_files(files.keys())
            return False
        status.update(
            label="Published" if published else "Not published",
            state="complete" if published else "error",
        )
        (st.success if published else st.warning)(f"{detail}\n\n{pr_url}" if pr_url else detail)
        if not published:
            revert_local_files(files.keys())
        return published


def order_picker(key_prefix, known_orders, detected_order):
    """
    Selectbox over orders already in use, plus "Unknown" and a manual write-in — because a
    genuinely new order (like Phasmatodea for the first stick insect card) won't be in
    `known_orders` yet, and a dropdown alone can't offer something not already in the data.
    Pre-selects `detected_order` (from guess_order_from_technical) when there is one: exactly if
    it's already a known order, or pre-fills the write-in field with it otherwise so the admin
    only has to confirm, not retype.
    """
    options = known_orders + [ORDER_UNKNOWN_LABEL, ORDER_OTHER_LABEL]
    if detected_order and detected_order in known_orders:
        default_index = known_orders.index(detected_order)
    elif detected_order:
        default_index = len(known_orders) + 1  # ORDER_OTHER_LABEL
    else:
        default_index = len(known_orders)  # ORDER_UNKNOWN_LABEL

    # Keyed on detected_order too, not just key_prefix: st.selectbox only honours a fresh
    # `index=` the first time a given key renders — a new PDF upload landing on the *same* key
    # (e.g. detected_order going from None to "Phasmatodea") would otherwise keep showing
    # whatever the first render defaulted to, same class of bug fixed earlier for text_input.
    choice = st.selectbox(
        "Order", options, index=default_index, key=f"{key_prefix}_order_select_{detected_order}"
    )
    if detected_order and choice == ORDER_OTHER_LABEL:
        st.caption(f"Detected from the technical report: `{detected_order}`")
    if choice == ORDER_OTHER_LABEL:
        manual = st.text_input(
            "Order (manual entry)",
            value=detected_order or "",
            key=f"{key_prefix}_order_manual_{detected_order}",
        )
        return manual.strip() or None
    if choice == ORDER_UNKNOWN_LABEL:
        return None
    return choice


st.set_page_config(page_title="dudus-app intake", layout="wide")
st.title("dudus-app admin intake")
st.caption(
    "Local-only authoring tool — for entering already-researched content (via /dudus or "
    "/dudusonline), not for researching a species itself."
)

tab_new, tab_existing, tab_batch = st.tabs(["Add new card", "Existing cards", "Batch"])

with tab_new:
    if "new_card_message" in st.session_state:
        st.success(st.session_state.pop("new_card_message"))

    st.session_state.setdefault("photo_uploader_version", 0)
    st.session_state.setdefault("lay_report_uploader_version", 0)

    existing_cards = load_cards()
    known_orders = sorted({c["order"] for c in existing_cards if c["order"]})

    st.subheader("Lay report")
    lay_report = st.file_uploader(
        "Upload the lay-audience PDF (from /dudus or /dudusonline)",
        type=["pdf"],
        key=f"new_lay_report_{st.session_state.lay_report_uploader_version}",
    )
    parsed_title, parsed_sections, parse_error = None, [], None
    if lay_report is not None:
        parsed_title, parsed_sections, parse_error = parse_lay_report(lay_report.getvalue())
        if parse_error:
            st.error(parse_error)
        else:
            st.success(f"Parsed '{parsed_title}' — {len(parsed_sections)} section(s).")
            with st.expander("Preview parsed sections"):
                for s in parsed_sections:
                    st.markdown(f"**{s['heading']}**")
                    st.write(s["body"])

    st.subheader("Photo")
    uploaded_photo = st.file_uploader(
        "Upload a pre-cropped photo (optional)",
        type=["jpg", "jpeg", "png"],
        key=f"new_photo_{st.session_state.photo_uploader_version}",
    )
    preview_img, photo_warning = (None, None)
    if uploaded_photo is not None:
        preview_img, photo_warning = process_photo(uploaded_photo)
        st.image(preview_img, caption="After metadata strip + 3:2 pad", width=400)
        if photo_warning:
            st.warning(photo_warning)

    st.subheader("Order")
    detected_order = None
    if parsed_title and lay_report is not None:
        detected_order = guess_order_from_technical(
            find_technical_pdf_path(parsed_title, lay_report.name)
        )
    resolved_order = order_picker("new", known_orders, detected_order)

    st.caption(
        "Everything else (scientific name, family, taxon rank, sourcing) has no edit UI yet — "
        "left as placeholder values for now, to fill in by hand until that exists."
    )

    st.divider()
    if st.button("Create card", type="primary"):
        errors = []
        if lay_report is None:
            errors.append("A lay report PDF is required.")
        elif parse_error:
            errors.append(parse_error)

        card_id = None
        if parsed_title:
            card_id = slugify(parsed_title)
            if not card_id:
                errors.append(f"Couldn't derive a usable id from title '{parsed_title}'.")
            elif any(c["id"] == card_id for c in existing_cards):
                errors.append(f"A card with id '{card_id}' already exists (from title '{parsed_title}').")

        if errors:
            for e in errors:
                st.error(e)
        else:
            photo_ref = None
            if uploaded_photo is not None:
                ext = "png" if uploaded_photo.type == "image/png" else "jpg"
                photo_ref = save_photo(preview_img, card_id, ext)

            new_card = order_card(
                {
                    "id": card_id,
                    "common_name": parsed_title,
                    "scientific_name": None,
                    "family": None,
                    "order": resolved_order,
                    "taxon_rank": DEFAULT_TAXON_RANK,
                    "sourcing": DEFAULT_SOURCING,
                    "sections": parsed_sections,
                    "source_report_ref": {
                        "technical": find_technical_ref(parsed_title, lay_report.name),
                        "lay": f"{parsed_title}/{lay_report.name}",
                    },
                    "photo_ref": photo_ref,
                    "reviewed_by": None,
                    "reviewed_at": None,
                }
            )
            existing_cards.append(new_card)
            save_cards(existing_cards)

            publish_files = {"src/data/card_index.json": serialize_cards(existing_cards)}
            if photo_ref:
                publish_files[f"public{photo_ref}"] = (PHOTOS_DIR / Path(photo_ref).name).read_bytes()
            do_publish(
                publish_files,
                commit_message=f"Add card: {parsed_title} ({card_id})",
                pr_title=f"Add card: {parsed_title}",
                pr_body=f"Automated content-only PR from tools/dudu-intake — no version bump (see #34). Adds '{parsed_title}' ({card_id}).",
            )

            st.session_state.photo_uploader_version += 1
            st.session_state.lay_report_uploader_version += 1
            # st.rerun() below aborts this script run immediately, so a message shown here would
            # never actually reach the browser — stash it and show it after the rerun instead.
            st.session_state.new_card_message = f"Added '{parsed_title}' ({card_id}) to card_index.json."
            st.rerun()

with tab_existing:
    if "existing_card_message" in st.session_state:
        st.success(st.session_state.pop("existing_card_message"))

    cards = load_cards()
    known_orders_existing = sorted({c["order"] for c in cards if c["order"]})
    if not cards:
        st.info("No cards yet.")
    for card in cards:
        with st.expander(f"{card['common_name']} ({card['id']})"):
            left, right = st.columns([1, 2])
            with left:
                if card["photo_ref"]:
                    photo_path = REPO_ROOT / "public" / card["photo_ref"].lstrip("/")
                    if photo_path.exists():
                        st.image(str(photo_path), width=250)
                    else:
                        st.warning(f"photo_ref set but file missing: {card['photo_ref']}")
                else:
                    st.write("No photo yet.")

            with right:
                replacement = st.file_uploader(
                    "Add / replace photo",
                    type=["jpg", "jpeg", "png"],
                    key=f"upload_{card['id']}",
                )
                if replacement is not None:
                    new_img, warn = process_photo(replacement)
                    st.image(new_img, caption="After metadata strip + 3:2 pad", width=300)
                    if warn:
                        st.warning(warn)
                    if st.button("Save photo", key=f"save_{card['id']}"):
                        old_photo_ref = card["photo_ref"]
                        delete_photo(old_photo_ref)
                        ext = "png" if replacement.type == "image/png" else "jpg"
                        card["photo_ref"] = save_photo(new_img, card["id"], ext)
                        save_cards(cards)

                        publish_files = {
                            "src/data/card_index.json": serialize_cards(cards),
                            f"public{card['photo_ref']}": (
                                PHOTOS_DIR / Path(card["photo_ref"]).name
                            ).read_bytes(),
                        }
                        if old_photo_ref and old_photo_ref != card["photo_ref"]:
                            publish_files[f"public{old_photo_ref}"] = None
                        do_publish(
                            publish_files,
                            commit_message=f"Update photo: {card['common_name']} ({card['id']})",
                            pr_title=f"Update photo: {card['common_name']}",
                            pr_body="Automated content-only PR from tools/dudu-intake — no version bump (see #34).",
                        )

                        st.session_state.existing_card_message = f"Photo saved for {card['common_name']}."
                        st.rerun()

                if card["photo_ref"]:
                    confirm = st.checkbox("Confirm removal", key=f"confirm_{card['id']}")
                    if st.button(
                        "Remove photo", key=f"remove_{card['id']}", disabled=not confirm
                    ):
                        old_photo_ref = card["photo_ref"]
                        delete_photo(old_photo_ref)
                        card["photo_ref"] = None
                        save_cards(cards)

                        do_publish(
                            {
                                "src/data/card_index.json": serialize_cards(cards),
                                f"public{old_photo_ref}": None,
                            },
                            commit_message=f"Remove photo: {card['common_name']} ({card['id']})",
                            pr_title=f"Remove photo: {card['common_name']}",
                            pr_body="Automated content-only PR from tools/dudu-intake — no version bump (see #34).",
                        )

                        st.session_state.existing_card_message = f"Photo removed for {card['common_name']}."
                        st.rerun()

            st.divider()
            st.write("**Update content from a corrected/revised report**")
            content_update = st.file_uploader(
                "Replace lay report",
                type=["pdf"],
                key=f"content_update_{card['id']}",
            )
            if content_update is not None:
                new_title, new_sections, content_parse_err = parse_lay_report(content_update.getvalue())
                if content_parse_err:
                    st.error(content_parse_err)
                else:
                    st.success(f"Parsed '{new_title}' — {len(new_sections)} section(s).")
                    with st.expander("Preview parsed sections"):
                        for s in new_sections:
                            st.markdown(f"**{s['heading']}**")
                            st.write(s["body"])
                    st.caption(
                        f"Keeps id (`{card['id']}`), photo, order, and other metadata unchanged — "
                        "only common_name, sections, and source_report_ref.lay/technical are replaced."
                    )
                    if st.button("Update card content", key=f"update_content_{card['id']}"):
                        card["common_name"] = new_title
                        card["sections"] = new_sections
                        card["source_report_ref"] = {
                            "technical": find_technical_ref(new_title, content_update.name),
                            "lay": f"{new_title}/{content_update.name}",
                        }
                        # The old review no longer describes this content — stale until re-reviewed.
                        card["reviewed_by"] = None
                        card["reviewed_at"] = None
                        save_cards(cards)

                        do_publish(
                            {"src/data/card_index.json": serialize_cards(cards)},
                            commit_message=f"Update card content: {new_title} ({card['id']})",
                            pr_title=f"Update card content: {new_title}",
                            pr_body="Automated content-only PR from tools/dudu-intake — no version bump (see #34/#52).",
                        )

                        st.session_state.existing_card_message = f"Content updated for {new_title}."
                        st.rerun()

            st.divider()
            st.write("**Order**")
            technical_ref = card["source_report_ref"].get("technical")
            technical_path_existing = None
            if isinstance(technical_ref, str) and technical_ref:
                candidate = DUDUS_ROOT / technical_ref
                technical_path_existing = candidate if candidate.exists() else None
            order_default = card["order"] or guess_order_from_technical(technical_path_existing)
            new_order = order_picker(f"existing_{card['id']}", known_orders_existing, order_default)
            if new_order != card["order"]:
                if st.button("Update order", key=f"update_order_{card['id']}"):
                    card["order"] = new_order
                    save_cards(cards)
                    do_publish(
                        {"src/data/card_index.json": serialize_cards(cards)},
                        commit_message=f"Update order: {card['common_name']} ({card['id']}) -> {new_order}",
                        pr_title=f"Update order: {card['common_name']}",
                        pr_body="Automated content-only PR from tools/dudu-intake — no version bump (see #34/#52).",
                    )
                    st.session_state.existing_card_message = f"Order updated for {card['common_name']}."
                    st.rerun()

            st.divider()
            confirm_delete = st.checkbox(
                "Confirm deletion — removes this card and its photo file",
                key=f"confirm_delete_{card['id']}",
            )
            if st.button(
                "Delete card permanently",
                key=f"delete_{card['id']}",
                disabled=not confirm_delete,
            ):
                old_photo_ref = card["photo_ref"]
                delete_photo(old_photo_ref)
                remaining = [c for c in cards if c["id"] != card["id"]]
                save_cards(remaining)

                publish_files = {"src/data/card_index.json": serialize_cards(remaining)}
                if old_photo_ref:
                    publish_files[f"public{old_photo_ref}"] = None
                do_publish(
                    publish_files,
                    commit_message=f"Delete card: {card['common_name']} ({card['id']})",
                    pr_title=f"Delete card: {card['common_name']}",
                    pr_body="Automated content-only PR from tools/dudu-intake — no version bump (see #34).",
                )

                st.session_state.existing_card_message = (
                    f"Deleted '{card['common_name']}' ({card['id']})."
                )
                st.rerun()

with tab_batch:
    if "batch_message" in st.session_state:
        st.success(st.session_state.pop("batch_message"))

    st.session_state.setdefault("batch_lay_uploader_version", 0)

    st.subheader("Add multiple cards")
    st.caption(
        "The whole batch publishes as a single PR — one CI run instead of one per card, at the "
        "cost that a single failed check blocks every card in the batch together, not just the "
        "one that broke something."
    )
    batch_cards_now = load_cards()
    known_orders_batch = sorted({c["order"] for c in batch_cards_now if c["order"]})

    batch_files = st.file_uploader(
        "Upload multiple lay-audience PDFs",
        type=["pdf"],
        accept_multiple_files=True,
        key=f"batch_lay_reports_{st.session_state.batch_lay_uploader_version}",
    )

    batch_rows = []
    seen_ids_this_batch = set()
    if batch_files:
        for i, f in enumerate(batch_files):
            title, sections, parse_err = parse_lay_report(f.getvalue())
            with st.container(border=True):
                st.write(f"**{f.name}**")
                if parse_err:
                    st.error(parse_err)
                    batch_rows.append({"error": parse_err})
                    continue

                card_id = slugify(title)
                dup_err = None
                if any(c["id"] == card_id for c in batch_cards_now):
                    dup_err = f"id '{card_id}' already exists on the live site."
                elif card_id in seen_ids_this_batch:
                    dup_err = f"id '{card_id}' is duplicated within this batch."
                seen_ids_this_batch.add(card_id)

                st.caption(f"Parsed '{title}' — {len(sections)} section(s).")
                if dup_err:
                    st.error(dup_err)

                col_a, col_b = st.columns(2)
                with col_a:
                    detected_order = guess_order_from_technical(
                        find_technical_pdf_path(title, f.name)
                    )
                    resolved_order = order_picker(f"batch_{i}", known_orders_batch, detected_order)
                with col_b:
                    photo_file = st.file_uploader(
                        "Photo (optional)", type=["jpg", "jpeg", "png"], key=f"batch_photo_{i}"
                    )
                    if photo_file is not None:
                        preview, warn = process_photo(photo_file)
                        st.image(preview, caption="After metadata strip + 3:2 pad", width=250)
                        if warn:
                            st.warning(warn)

                batch_rows.append(
                    {
                        "error": dup_err,
                        "title": title,
                        "sections": sections,
                        "card_id": card_id,
                        "order": resolved_order,
                        "photo_file": photo_file,
                        "lay_filename": f.name,
                    }
                )

    valid_batch_rows = [r for r in batch_rows if not r["error"]]
    if batch_rows:
        st.caption(f"{len(valid_batch_rows)} of {len(batch_rows)} ready to publish.")

    if st.button("Publish batch", type="primary", disabled=not valid_batch_rows):
        cards = load_cards()
        publish_files = {}
        added = []
        skipped = []
        for row in valid_batch_rows:
            if any(c["id"] == row["card_id"] for c in cards):
                skipped.append(row["card_id"])
                continue

            photo_ref = None
            if row["photo_file"] is not None:
                img, _ = process_photo(row["photo_file"])
                ext = "png" if row["photo_file"].type == "image/png" else "jpg"
                photo_ref = save_photo(img, row["card_id"], ext)
                publish_files[f"public{photo_ref}"] = (PHOTOS_DIR / Path(photo_ref).name).read_bytes()

            new_card = order_card(
                {
                    "id": row["card_id"],
                    "common_name": row["title"],
                    "scientific_name": None,
                    "family": None,
                    "order": row["order"],
                    "taxon_rank": DEFAULT_TAXON_RANK,
                    "sourcing": DEFAULT_SOURCING,
                    "sections": row["sections"],
                    "source_report_ref": {
                        "technical": find_technical_ref(row["title"], row["lay_filename"]),
                        "lay": f"{row['title']}/{row['lay_filename']}",
                    },
                    "photo_ref": photo_ref,
                    "reviewed_by": None,
                    "reviewed_at": None,
                }
            )
            cards.append(new_card)
            added.append(f"{row['title']} ({row['card_id']})")

        for card_id in skipped:
            st.warning(f"Skipped — '{card_id}' already exists (published elsewhere just now).")

        st.session_state.batch_lay_uploader_version += 1
        if added:
            save_cards(cards)
            publish_files["src/data/card_index.json"] = serialize_cards(cards)
            ok = do_publish(
                publish_files,
                commit_message="Add cards: " + ", ".join(added),
                pr_title=f"Add {len(added)} card(s): " + ", ".join(added),
                pr_body=(
                    "Automated content-only PR from tools/dudu-intake — no version bump "
                    f"(see #34/#40). Adds: {', '.join(added)}."
                ),
            )
            st.session_state.batch_message = (
                f"Batch add: {'published' if ok else 'not published'} ({len(added)} card(s))."
            )
        else:
            st.session_state.batch_message = "Nothing to publish — every card already existed."
        st.rerun()

    st.divider()
    st.subheader("Remove multiple cards")
    st.caption("The whole batch publishes as a single PR, same tradeoff as adding.")

    removal_candidates = load_cards()
    selected_for_removal = [
        c for c in removal_candidates
        if st.checkbox(f"{c['common_name']} ({c['id']})", key=f"batch_remove_{c['id']}")
    ]

    if selected_for_removal:
        confirm_batch_delete = st.checkbox(
            f"Confirm deletion of {len(selected_for_removal)} card(s) and their photos",
            key="confirm_batch_delete",
        )
        if st.button("Delete selected cards", disabled=not confirm_batch_delete):
            cards = load_cards()
            publish_files = {}
            removed = []
            selected_ids = {t["id"] for t in selected_for_removal}
            for target in selected_for_removal:
                card = next((c for c in cards if c["id"] == target["id"]), None)
                if card is None:
                    st.warning(f"Skipped — '{target['id']}' no longer exists (removed elsewhere just now).")
                    continue
                if card["photo_ref"]:
                    delete_photo(card["photo_ref"])
                    publish_files[f"public{card['photo_ref']}"] = None
                removed.append(f"{card['common_name']} ({card['id']})")

            if removed:
                remaining = [c for c in cards if c["id"] not in selected_ids]
                save_cards(remaining)
                publish_files["src/data/card_index.json"] = serialize_cards(remaining)
                ok = do_publish(
                    publish_files,
                    commit_message="Delete cards: " + ", ".join(removed),
                    pr_title=f"Delete {len(removed)} card(s): " + ", ".join(removed),
                    pr_body=(
                        "Automated content-only PR from tools/dudu-intake — no version bump "
                        f"(see #34/#40). Removes: {', '.join(removed)}."
                    ),
                )
                st.session_state.batch_message = (
                    f"Batch delete: {'published' if ok else 'not published'} ({len(removed)} card(s))."
                )
            else:
                st.session_state.batch_message = "Nothing to publish — no selected card still existed."
            st.rerun()
